plugins{id 'com.android.application'}android{namespace 'com.raynanapk.builder';compileSdk 34;defaultConfig{applicationId "com.raynanapk.builder";minSdk 24;targetSdk 34;versionCode 5;versionName "5.0"}compileOptions{sourceCompatibility JavaVersion.VERSION_17;targetCompatibility JavaVersion.VERSION_17}}dependencies{implementation 'androidx.appcompat:appcompat:1.6.1'}
