plugins { id "com.android.application" }
android {
    namespace "com.raynanapk.builder"
    compileSdk 34
    defaultConfig {
        applicationId "com.raynanapk.builder"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "11.0-V8-Money"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.android.tools.build:apksig:8.1.0"
    implementation "org.bouncycastle:bcprov-jdk15on:1.70"
    implementation "org.bouncycastle:bcpkix-jdk15on:1.70"
    implementation "com.google.android.gms:play-services-ads:22.5.0"
}
